### ISSUE TITLE
Learner.model_params will return weights with the wrong sign if sklearn is fixed

### ISSUE THREAD

**Issue by mheilman** [EducationalTestingService/skll#111]
Currently, sklearn appears to output coefficients with the wrong sign for SVR.  See https://github.com/scikit-learn/scikit-learn/issues/2933.

SKLL pull request #110 adds support to SKLL for printing SVR model weights and corrects the sign.  However, whenever sklearn is fixed, the correction should be removed.

**Comment by dan-blanchard** [comment]
This is in 0.16, so we need to fix it before next release.

**Comment by desilinguist** [comment]
Addressed by #243.
