### ISSUE TITLE
Need support for reading instance weights from feature files

### ISSUE THREAD

**Issue by doxav** [EducationalTestingService/skll#182]
I noticed that instance weights are not supported by Skll readers and writers. It is a key feature to deal with unbalanced data (or cost-sensitive learning additionally to matrix cost). ARFF supports it (http://weka.wikispaces.com/ARFF+(stable+version)#Instance weights in ARFF files ) and some Sklearn classifiers.

**Comment by desilinguist** [comment]
I think this still squarely belongs in the `help-wanted` category since we haven't seen a lot of demand for this internally.

**Comment by bndgyawali** [comment]
Please keep it open.

**Comment by aoifecahill** [comment]
keep it open please

**Comment by desilinguist** [comment]
I am going to close this since no one really seems to want this.
