### ISSUE TITLE
Remove decision tree and random forest learners from requires_dense set

### ISSUE THREAD

**Issue by dan-blanchard** [EducationalTestingService/skll#207]
Whenever the next version of scikit-learn comes out, it will support sparse input for decision trees and random forests, which is pretty great news.  This was added in scikit-learn/scikit-learn#3173.

Anyway, we'll need to update our `skll.learner._REQUIRES_DENSE` set to remove those learners from it to take advantage of this.

**Comment by dan-blanchard** [comment]
0.16 is out with this, so we should do it.

**Comment by desilinguist** [comment]
Addressed by #245.
