### ISSUE TITLE
Visualize results

### ISSUE THREAD

**Issue by dan-blanchard** [EducationalTestingService/skll#212]
A few people at PyData mentioned that it would be really cool if SKLL could generate graphs summarizing the results (in addition to spitting out the TSV file).  It would also be nice if we could generate colored confusion matrices like: ![this](http://www.mathworks.com/products/demos/machine-learning/confusion_matrix/Confusion_Matrix_01.png).

**Comment by brianray** [comment]
The HTML version is not so much the issue. The graphical versions I have questions...

Looking at the possible dependencies adding graphic output. For example here is from topmodel:

https://github.com/stripe/topmodel/blob/master/requirements.txt

the scikit learn example http://scikit-learn.org/stable/auto_examples/model_selection/plot_learning_curve.html also adds matplotlib

What are you thinking about adding dependencies. Should they be required or optional? If optional, I presume you know the impact on our code.

**Comment by desilinguist** [comment]
For a while now, I have had the idea of SKLL generating an ipython notebook
as a possible output. For another project, I am working on, I generate both
an iPython notebook and a dynamically rendered HTML file as outputs. It
seems to work really well. For people, who want to tinker around further,
they can play around in the notebook and others who just want graphical
outputs can just look at the HTML file.

**Comment by brianray** [comment]
@desilinguist for sure a ipython (jupyter) notebook would be ince; however, I think that should be a separate ticket. I think this can provide the html/graphics that goes into the notebook for sure.

**Comment by desilinguist** [comment]
Now that we have `seaborn` as an optional dependency, perhaps we can make this a possible option.

**Comment by desilinguist** [comment]
I am going to move this to 2.0 since IMO it's a big change and will be nice to tout for a v2.0.
