### ISSUE TITLE
Stop modifying global numpy random seed

### ISSUE THREAD

**Issue by mheilman** [EducationalTestingService/skll#220]
In `learner.train` and `learner.cross_validate`, the global numpy random seed is set.  This seems unnecessary since the randomized algorithms in scikit-learn generally take random seed arguments.  Can we remove these?

https://github.com/EducationalTestingService/skll/blob/5c113bca947082e2b56e41c8a13d7ab43d49160a/skll/learner.py#L907
https://github.com/EducationalTestingService/skll/blob/5c113bca947082e2b56e41c8a13d7ab43d49160a/skll/learner.py#L1393

**Comment by desilinguist** [comment]
Addressed by #245.
