### ISSUE TITLE
consider changing .ndj file extension

### ISSUE THREAD

**Issue by mheilman** [EducationalTestingService/skll#230]
I googled "newline delimited json", and it looks like "ldj" might be slightly more widely accepted than "ndj".

http://en.wikipedia.org/wiki/Line_Delimited_JSON

There is an amusing/annoying proliferation of names for this file format, but in a quick search, I didn't come across other mentions of "ndj".

Of course, this is really not important.

**Comment by dan-blanchard** [comment]
And of course http://jsonlines.org/ recommends `.jsonl`.  There are just dozens of extensions and names for the same format, unfortunately.  Maybe we should just accept all of them and change the default to `.ldj`?

**Comment by dan-blanchard** [comment]
And let us not forget [`.ndjson`](http://dataprotocols.org/ndjson/).

**Comment by desilinguist** [comment]
I think `.jsonlines` is pretty well-entrenched by now so I am not sure if this is something we can do.
