### ISSUE TITLE
When scikit-learn 0.18 comes out, we need to update our F1 metrics in __init__.py

### ISSUE THREAD

**Issue by dan-blanchard** [EducationalTestingService/skll#231]
scikit-learn/scikit-learn#4192 makes it so that setting `pos_label` to `None` is no longer necessary with binary datasets (because you'll have to use "binary" as the value for `average` to get the one-class version it returns now).  This will become the default behavior in 0.18, so we'll need to update things then.  This was brought up all the way back in #3.

**Comment by desilinguist** [comment]
Addressed by #330.
