### ISSUE TITLE
skll breaks importing missing class BaseLibLinear with scikit-learn 0.16

### ISSUE THREAD

**Issue by jkleint** [EducationalTestingService/skll#233]
`run_experiement` gives
```
ImportError: cannot import name BaseLibLinear
```

Seems this class was removed from scikit-learn.  This is with skll 1.0.1.

**Comment by dan-blanchard** [comment]
Thanks for reporting this. As of 1.0, each SKLL release is
intended/guaranteed to only work with a specific version of scikit-learn.
This makes it much simpler to replicate results. We will have a new release
that supports 0.16 soon.

**Comment by desilinguist** [comment]
This is related to #235

**Comment by desilinguist** [comment]
Addressed by #243.
