### ISSUE TITLE
Base estimators other than default are not supported for AdaBoost

### ISSUE THREAD

**Issue by benleong-ets** [EducationalTestingService/skll#238]
Can we use SKLL's AdaBoost with LogisticRegression as the weak learner? We are interested to test out LogisticRegression instead of DecisionTreeClassifier.

In the config file, I set the base_estimator to be `LogisticRegression` as follows:

```
fixed_parameters=[{'base_estimator':'LogisticRegression', 'algorithm':'SAMME'}]
```

But I got the following error:

```python
TypeError: Cannot clone object ''LogisticRegression'' (type <class 'str'>): it does not seem to be a scikit-learn estimator it does not implement a 'get_params' methods.
```

The input param is specified as a string but an object is needed. We can't do the conversion with the config file.

**Comment by desilinguist** [comment]
Addressed by #245.
