### ISSUE TITLE
cannot import name BaseLibLinear

### ISSUE THREAD

**Issue by MagicYoung** [EducationalTestingService/skll#241]
when I did:

from skll import Learner

it prompted "cannot import name BaseLibLinear"

Currently, BaseLibLinear is removed from sklearn.svm.base. Do I need to modify the source code of SKLL? I used pip to install skll. Thanks.

**Comment by aoifecahill** [comment]
Duplicate issue, see #233.

**Comment by aoifecahill** [comment]
Have you tried installing with scikit-learn 0.15.2?
