### ISSUE TITLE
Upgrade to Travis' container infrastructure

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#244]
Travis [says](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) that builds will be much, much faster if we switch to their container infrastructure instead of using the legacy infrastructure we are currently using. However, the container infrastructure does not allow the use of `sudo` which we use in our `.travis.yml` in two places: 
- when creating a `scratch` directory under the the `/`, and
- when symlinking `/dev/shm` to `/run/shm`

Is there any way we can get around those things and use the new infrastructure? @dan-blanchard?

**Comment by desilinguist** [comment]
According to Dan's blog post [here](http://dan-blanchard.roughdraft.io/7045057-quicker-travis-builds-that-rely-on-numpy-and-scipy-using-miniconda), it looks like the second bullet is to get around a multiprocessing bug in Travis. Is that still an issue?

**Comment by dan-blanchard** [comment]
We install SGE for some of our tests, so we will always need sudo for everything that happens in the script that installs it.

**Comment by desilinguist** [comment]
@dan-blanchard since we are not going to be using SGE anymore, can we migrate to the new Travis infrastructure?

**Comment by dan-blanchard** [comment]
Yeah, everything else should work fine.
