### ISSUE TITLE
Division by zero printing progress when there is only one example

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#253]
from `skll/data/readers.py` (Line 203, division by zero on line 217)

        # Remember total number of examples for percentage progress meter
        total = ex_num

        # Convert everything to numpy arrays
        ids = np.array(ids)
        labels = np.array(labels)

        def feat_dict_generator():
            with open(self.path_or_list, 'r' if PY3 else 'rb') as f:
                for ex_num, (_, _, feat_dict) in enumerate(self._sub_read(f)):
                    yield feat_dict
                    if ex_num % 100 == 0:
                        self._print_progress('{:.8}%'.format(100 * ((ex_num +
                                                                     1) /
                                                                    total)))
                self._print_progress("100%")

**Comment by desilinguist** [comment]
Fixed by #254
