### ISSUE TITLE
generate_predictions3 throwing error

### ISSUE THREAD

**Issue by bndgyawali** [EducationalTestingService/skll#255]
I am getting the following error while running generate_predictions using `LogisticRegression` model
```

Traceback (most recent call last):
  File "/opt/python/3.4/bin/generate_predictions3", line 6, in <module>
    sys.exit(main())
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/utilities/generate_predictions.py", line 159, in main
    for pred in predictor.predict(feature_set):
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/utilities/generate_predictions.py", line 63, in predict
    preds = self._learner.predict(data)
  File "/opt/python/3.4/lib/python3.4/site-packages/skll/learner.py", line 1271, in predict
    else self._model.predict(xtest))
  File "/opt/python/3.4/lib/python3.4/site-packages/sklearn/linear_model/base.py", line 228, in predict
    return self.classes_[indices]
AttributeError: 'LogisticRegression' object has no attribute 'classes_'
```

**Comment by bndgyawali** [comment]
This may not be a problem. This was generated while using the model generated by older `skll` version. I regenerated the model and it is now working fine.

**Comment by orensig** [comment]
@bndgyawali can you explain how you regenrated the model, casue I'm getting the same error

**Comment by desilinguist** [comment]
@orensig I think by "regenerated", @bndgyawali just meant that he retrained the model.

**Comment by bndgyawali** [comment]
@orensig @desilinguist sorry, I didn't notice this. I think I retrained the model using python3. It's been a long time, so do not remember exactly.

**Comment by orensig** [comment]
@desilinguist @bndgyawali I would be very happy to learn how to retrain the model I'm using (it's a model built by someone else). I have the trained model files.

**Comment by desilinguist** [comment]
Was it trained using SKLL? Do you have the config file that was used to train the model?

**Comment by orensig** [comment]
It was trained by using Scikit-Learn Logistic regression. I don't have the config file.

**Comment by desilinguist** [comment]
If it was trained using scikit-learn directly, I don't think you can use SKLL to retrain it. Sorry.

**Comment by orensig** [comment]
Is there any other way to handle the error:
AttributeError: 'LogisticRegression' object has no attribute 'classes_'
