### ISSUE TITLE
Add `pandas` data frame helper 

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#261]
It would be nice to have a helper method in the `FeatureSet` class (`FeatureSet.from_data_frame`, may be?) that would let you convert a pandas data frame to a FeatureSet. I already have the code to do this in another project so it shouldn't be a lot of work. I imagine it would really be useful to people who use the SKLL API but want to just use the data that they already have in a data frame.

Ideally, you would want all the main methods to accept data frames in addition to FeatureSets but that would be a lot of work. I think this is a nice workaround in the meanwhile.

**Comment by desilinguist** [comment]
Sorry for all the mis-clicks for the milestones. GitHub apparently wants to keep a record of everything :)

**Comment by dan-blanchard** [comment]
I think this is a nice idea, but it should be done in such a way that we don't actually need pandas as a prereq.

**Comment by desilinguist** [comment]
Looking at my code, it will work just fine with the `DataFrame` object itself without relying on `pandas` to be available. However, I am not sure what the big deal is about using `pandas` as a prereq. It actually has lots of nice functionality.

**Comment by dan-blanchard** [comment]
Eh, I just don't like when packages have requirements that are for optional things.  It's like how we'll currently use GridMap if it's installed, but it's not a requirement.

**Comment by desilinguist** [comment]
I think at this point people who use `skll` but not `pandas` are going to be a very small minority. Plus, I can totally see adding a lot more functionality to `skll` by borrowing more from `pandas` built-in functionality.

**Comment by dmnapolitano** [comment]
:+1:

**Comment by dmnapolitano** [comment]
Question: do we want to make `pandas` a `skll` requirement?

**Comment by dan-blanchard** [comment]
> I think this is a nice idea, but it should be done in such a way that we don't actually need pandas as a prereq.

:smile:

**Comment by desilinguist** [comment]
Addressed by #292.
