### ISSUE TITLE
pretty print confusion matrix with labels

### ISSUE THREAD

**Issue by bwriordan** [EducationalTestingService/skll#271]
A printed confusion matrix with labels for rows and columns would be useful. This is not in sci-kit and seems to be implemented fairly often, and so might make a nice SKLL feature. Cf.:
https://gist.github.com/zachguo/10296432
https://pypi.python.org/pypi/pandas_confusion/

**Comment by dan-blanchard** [comment]
We output a confusion matrix as part of the [standard `run_experiment` output](http://skll.readthedocs.org/en/latest/tutorial.html#examine-the-results).  Is there something about it that doesn't meet your needs?

**Comment by bwriordan** [comment]
Thanks, yes, it would be helpful to have modular code that pretty-prints the confusion matrix alone, without the other metrics next to it as the output does now. It would be useful if the function _create_learner_result_dicts() in experiments.py could be modularized so that there is an independent print_confusion_matrix() function. This function could then be exposed so that code outside of SKLL could query SKLL results for just the confusion matrix.
