### ISSUE TITLE
Need to document that FeatureSets will be unequal when instances are ordered differently

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#272]
If we read in two feature files where all the instances are exactly the same but just ordered differently, the resulting FeatureSets will not be equal to each other. Is this to be expected? Should ordering really matter for a FeatureSet or should two FeatureSets be deemed equal as long as all the feature values are the same for the same instances? 

Now that I think about it, I am not sure we can really address this issue because this would mean re-ordering/sorting stuff after the file has been read which could be very inefficient for large feature files. However, we should probably document this in the API and the code - that ordering matters for FeatureSets.

**Comment by dan-blanchard** [comment]
Yeah, part of how we're efficient is by not sorting things.  Also, as we all know, example order matters a lot for learning, so I think we should just document that ordering matters.

**Comment by desilinguist** [comment]
Addressed by #294.
