### ISSUE TITLE
Conda update to numpy/scipy will break SKLL conda package on Linux

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#283]
Recently, conda switched to using (the so-far proprietary) mkl backend as the default for their numpy and scipy packages. It already breaks travis builds (see #282). What's worse is that this is also going to impact anyone who installs the SKLL conda package on Linux since that will also install the `mkl` backend by default. So, we will need to fix the recipe to use `nomkl` on Unix platforms.

**Comment by aoifecahill** [comment]
Since our instructions say to download the conda package from @dan-blanchard's channel, I think he should be the one to address this ;)

**Comment by desilinguist** [comment]
This is already addressed by the recipes but conda has also improved their mkl stuff a bit more so the recipes can be merged back into a single recipe again.
