### ISSUE TITLE
Non-integer labels for classification

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/skll#285]
Non-integer numeric labels for classification experiments are treated as integers without any warning. For example, [1, 1.6, 1] becomes [1, 1, 1].

**Comment by aloukina** [comment]
This is not true.

**Comment by aoifecahill** [comment]
Phew :)

**Comment by aloukina** [comment]
It does happen if you generate test_fs and pass it to learner.evaluate() directly: not sure if this scenario is possible.

**Comment by desilinguist** [comment]
That seems like something you would do a lot when using the API. We do it in RSMTool (albeit for regression)

**Comment by desilinguist** [comment]
@aoifecahill confirmed that this is not a problem and just to be sure we added another test for this in #295.

**Comment by aloukina** [comment]
For future reference: the float to integer conversion happens if one creates data using make_classification_data and then changes the labels by using indices:
`train_fs, test_fs = make_classification_data(num_labels=3, train_test_ratio=0.8)
test_fs.labels[-1]=1.5
`
