### ISSUE TITLE
Explore online learning as an option

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#305]
There is a small set of learners (`Perceptron`, `PassiveAggressiveRegressor`, `PassiveAggressiveClassifier`, `SGDRegressor`, `SGDClassifier`, `MultinomialNB`, `BernoulliNB`, and `MiniBatchKMeans`, to be exact) that support a `partial_fit` method, i.e., online learning. This is a really nice feature if your data is too big to fit in memory, so it would be great if it were an option in the configuration file (for the learners mentioned above). As part of this issue, I would probably try to add in `BernoulliNB` and the `PassiveAggressiveRegressor/Classifier` learners since they have not been made available in SKLL. I believe every other one is provided, though.

**Comment by mulhod** [comment]
@cml54 Just wanted to copy you on this since I know you asked about it

**Comment by mulhod** [comment]
Not sure how feasible this even is, but I'd like to keep it open.

**Comment by desilinguist** [comment]
@mulhod do you have a time frame for this in mind?
