### ISSUE TITLE
No warning is raised if ablation flag is used with train_file/test_file

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#313]
A warning should be raised if a user has specified a `train_file`/`test_file` in their config file and then tries to use ablation when running `run_experiment`. No `featuresets` are specified, so there's nothing to ablate. No errors occur and the experiments seem to finish fine, but the results don't make much sense in terms of the labels that are given to them. Probably a warning should be raised and the use of the ablation flag ignored OR an exception should be raised since it's unclear what the user is trying to do. Perhaps mention could be made that the user will have to specify a `train_directory`/`test_directory` in order to specify `featuresets` and/or that, in order to be able to ablate with each feature in a file, a different file will (currently) have to be made for each individual feature and specified as a `featureset` separately. (This last issued is related to another issue and the behavior might change if dealt with.)

**Comment by desilinguist** [comment]
Addressed by #392.
