### ISSUE TITLE
Add feature selection

### ISSUE THREAD

**Issue by bndgyawali** [EducationalTestingService/skll#316]
I had thought about adding `feature selection` into SKLL. 

For example: we have feature sets `word_trigrams`, `pos_tags` and want to apply `SelectKBest` feature selection method with scoring function `chi2` and `k=100` on `word_trigrams`

Add a new field in config file: 
`feature_selection = {"word_trigrams": {"selection_approach": "SelectKBest", "scoring_func": "chi2","k": 100}}`

While converting the feature into numpy array: instead of using `vectorizer` in `readers.py`, use `pipeline`. `Pipeline` will be a chain of `vectorizer` and `feature selection` or `vectorizer` only depending upon whether the feature selection has to be done or not.

Since there are many feature selection methods available, and they have their own parameters, it may be difficult to add all the methods in a single go, we can incrementally add the feature selection methods.

I can work on this if you think this is a good addition to SKLL. Please let me know your views on this and also if there is better way of doing it.

**Comment by GillesJ** [comment]
Instead of only adding `feature selection`, adding `pipeline` functionality seems like the way to go. Many people use non-standard sklearn compatible code that functions in a pipeline.

+1

**Comment by aoifecahill** [comment]
I think this is still a nice to have

**Comment by desilinguist** [comment]
So, should we be renaming this issue to "Add support for pipelines"? And if so, that seems like a major task. Who would work on it? @bndgyawali do you have time for this?
