### ISSUE TITLE
param_grids documentation for SVC gamma is missing 'auto'

### ISSUE THREAD

**Issue by bwriordan** [EducationalTestingService/skll#334]
Documentation does not have 'auto':
https://github.com/EducationalTestingService/skll/blob/stable/doc/run_experiment.rst

Line 99 has 'auto': https://github.com/EducationalTestingService/skll/blob/b3228e242301f0ff8b349869e30489cadf53285e/skll/learner.py

**Comment by desilinguist** [comment]
Pull request welcome.

**Comment by desilinguist** [comment]
Addressed by #337.
