### ISSUE TITLE
predictions files have .predictions extension instead of .tsv

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#341]
Predictions files output by SKLL end with the extension `.predictions` (though they are really just TSV files). Beside the fact that it's a bit unusual as an extension and doesn't give any information about how it's formatted (is it CSV or TSV?), it sometimes presents a problem if other code is expecting a familiar extension and it doesn't know what to do with this type of file, e.g. in [`rsmtool`](https://github.com/EducationalTestingService/rsmtool/issues/86). It might be better if the predictions file ended with `_predictions.tsv` instead.

**Comment by Lguyogiro** [comment]
I've made the change in my branch to write predictions files with the suffix "_prediction.tsv". There is a static predictions file in 'tests/other' and one under 'tests/backward_compatibility', that are read during testing. There is no issue with reading predictions files ending in '.predictions', but I'm wondering if I should rename either of these for consistency. I think it makes sense to leave the 'backward_compatibility' predictions file with the old naming convention, but I'm curious if there is any pushback about renaming the other one.

**Comment by desilinguist** [comment]
@Lguyogiro thanks for taking this on! Yes, please rename the non-"backward compatibility" files. However, IMO, the name should be `_predictions.tsv` (plural) not singular.

**Comment by Lguyogiro** [comment]
Yes, my mistake, that was a typo. It will be `_predictions.tsv`.

**Comment by Lguyogiro** [comment]
This issue is addressed by PR #347 .
