### ISSUE TITLE
`compute_eval_from_predictions` should handle prediction files with probabilities

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#344]
Currently, it can _only_ handle the prediction files with the labels but not the ones that are generated when `probability=True` in the config file.

**Comment by Lguyogiro** [comment]
There are potentially multiple ways to arrive at a prediction given class probabilities (e.g. class with highest probability, custom class-specific thresholds, Expected Value, etc.)). Should we offer a way to indicate this in `compute_eval_from_prediction`? Or does it make more sense for now to always treat the highest-probability class as the prediction?

**Comment by aoifecahill** [comment]
How complicated would it get to allow several ways to do this? Perhaps we could start with highest probability (as the default) and also consider an expected value (though this will only be possible for a subset of classification labels).

**Comment by Lguyogiro** [comment]
That suggestion doesn't sound too complicated. I'll start with the highest-probability class, and include support for expected-value for numeric classes.

**Comment by Lguyogiro** [comment]
Also, if the classes have equal probabilities, should I select a class at random? or should there be a 'default class' argument for this case?

**Comment by Lguyogiro** [comment]
Addressed by #395
