### ISSUE TITLE
allow plotting of learning curves from summary files

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#346]
If you run a learning_curve experiment where the plots cannot be generated (e.g. submitting a job on a grid)) the experiment core dumps while trying to generate the plot. 

It would be nice to have an entry point in skll that would take the output summary files that do get generated and produce the plots separately (on a machine that does have a display for matplotlib).

**Comment by desilinguist** [comment]
@aoifecahill when you say summary files, you mean the learning curve output files right? So, the workflow would be as follows: 

1. Create environment on the server that does not have `pandas` and `seaborn`. 
2. Run learning curve experiment on the server using this environment. This would produce the learning curve output files but _not_ the plots.
3. Generate the learning curve plots later using a new utility script on a different machine.

Does that sound right?

**Comment by aoifecahill** [comment]
Yes, that sounds about right. Even if pandas and seaborn are installed in the original environment it doesn't always work (depending on how you are logged into the server). So if the plot generation fails, it would be nice to be able to generate them after the fact without rerunning the entire experiment.

**Comment by desilinguist** [comment]
Addressed by #396.
