### ISSUE TITLE
Replace `prettytable` with something more modern and actively maintained.

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#356]

**Comment by desilinguist** [comment]
Still need to address this.

**Comment by Lguyogiro** [comment]
I recently stumbled upon `python-tabulate`, which looks like it could be a candidate. I don't know many details yet. As far as it being actively maintained, there seem to be pretty consistent commits over the last few months and as recently as January 2018: [https://bitbucket.org/astanin/python-tabulate/src](url)

**Comment by desilinguist** [comment]
Looks nice but the version on `conda-forge` seems to be way behind.

**Comment by desilinguist** [comment]
Keep it open please.

**Comment by aoifecahill** [comment]
keep it open please

**Comment by desilinguist** [comment]
Keep it open please.

**Comment by desilinguist** [comment]
It does look like the latest release of `tabulate` is now in conda so perhaps this is the best we can do.

**Comment by desilinguist** [comment]
Addressed by #467.
