### ISSUE TITLE
Possibly add skll to conda-forge channel?

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#359]
Once we fully switch to python 3.6, we will need to install SKLL this way:

```
conda install -c defaults -c conda-forge -c desilinguist python=3.6 skll
```

We need three channels in that order because:

1. We want to use the `mkl`-based versions of numpy, scipy, and scikit-learn since that's known to be faster than `openblas` which is what `conda-forge` uses as the BLAS backend. And `mkl` is only available in `defaults`.
2. We need some packages like `ruamel.yaml` and `prettytable` which are _only_ available on `conda-forge` for all three platforms (Linux, Windows, and macOS). Earlier I used to build these and upload these to my conda channel but I haven't been able to compile some of them on Windows recently.
3. `skll` lives in my channel

If we get `skll` added to `conda-forge` channel then we will only need 2 channels in the command: 

```
conda install -c defaults -c conda-forge python=3.6 skll
```

Not sure how high priority this should be. Thoughts?

**Comment by aoifecahill** [comment]
I think it would be nice to have it be in `conda-forge`. How much work is involved in getting it added there? And how easy is it to update there?

**Comment by desilinguist** [comment]
keep this open for now

**Comment by desilinguist** [comment]
Keep it open.

**Comment by desilinguist** [comment]
keep it open please/

**Comment by desilinguist** [comment]
Open it
