### ISSUE TITLE
send logging output to logfile instead of console

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#369]
Currently all logging statements are directed to the console, and there are a small number of print statements that write to the log file. 

I think it would make more sense for the logging statements currently being sent to the console to also appear in that log file so that we have a record of them after an experiment has run (without manually redirecting the output of `run_experiment`.).

**Comment by aoifecahill** [comment]
sure :)

**Comment by desilinguist** [comment]
Addressed by #380.
