### ISSUE TITLE
Standardized docstrings to NumPy-style

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/skll#373]
This may be a low priority, but it would be useful to standardize all of the docstrings in `SKLL` to `numpy` style, and to make sure that all inputs and outputs are consistently documented.

There are a number of methods in the `SKLLConfigParser` class, for example, that do not have docstrings or whose docstrings do not describe the method's arguments and return values. These are all private methods, but it would still be useful for the purpose of code maintenance and PR reviews to document them.

**Comment by desilinguist** [comment]
I'd appreciate if someone else could help tackle this issue.

**Comment by desilinguist** [comment]
Addressed by #397.
