### ISSUE TITLE
Add support for Multi-layer Perceptron regressor and classifier

### ISSUE THREAD

**Issue by Lguyogiro** [EducationalTestingService/skll#375]
It would be great to expose `MLPClassifier` and `MLPRegressor`.

- [http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier](url)
-  [http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html#sklearn.neural_network.MLPRegressor](url)

**Comment by desilinguist** [comment]
Addressed by #377.
