### ISSUE TITLE
Remove default tuning objective and make it a required field.

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#381]
Right now, the default metric for _all_ learners is `f1_score_micro` which doesn't make sense for regressors. 

(Note: This issue is related to but separate from #350.)

**Comment by desilinguist** [comment]
I am not really sure how to do this honestly since the default objective is set during config parsing and to override the defaults means actually checking whether all the learners are regressors and doing so means actually instantiating them early during config parsing itself into objects to check their `_estimator_type` attribute. This seems wasteful to me. 

I am trying to think of a better solution. Suggestions and thoughts welcome.

**Comment by aoifecahill** [comment]
Couldn't we do something a little less sophisticated and just hard code the string names of the regressors and classifiers wrapped by skll? We do that in other places for other reasons. 

It wouldn't work for a custom learner though.

**Comment by desilinguist** [comment]
So, then we have another place where we have to update the names of learners when we add new ones? I am not a fan of that approach - what if someone forgets to update the list? Then we need to add more tests for that scenario and basically increase the complexity of the codebase. Plus it wouldn't work for a custom learner like you said.

May be we should just _not_ have a default objective at all? If you don't specify an objective in the config file, you get an early error during config parsing itself. This way, you don't get an incomplete experiment and the responsibility of the objective is on the user itself. 

It would break backward compatibility though for old config files which is not ideal either.

**Comment by aoifecahill** [comment]
Well if we don't want to add complexity to the config reading by doing the checks there, then I think the next best thing is to not have a default, but I suppose that would have to be part of a `2.0` release if it's breaking backwards compatibility.

**Comment by desilinguist** [comment]
Agreed. Let's do that in v2.0.

**Comment by desilinguist** [comment]
We will fix this in v2.0. Keep it open.

**Comment by aoifecahill** [comment]
keep it open

**Comment by desilinguist** [comment]
keep it open please

**Comment by desilinguist** [comment]
As part of this issue, I am also going to get rid of the `objective` field and keep only the `objectives` field. This would simplify the code a lot and also improve consistency with the `metrics` option (both being lists of scoring functions).

**Comment by desilinguist** [comment]
Addressed by #458.
