### ISSUE TITLE
add GaussianProcessRegressor and GaussianProcessClassifier

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#393]
http://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html#sklearn.gaussian_process.GaussianProcessRegressor

**Comment by desilinguist** [comment]
@aoifecahill I am assuming it's okay to remove this from the 1.5 milestone?

**Comment by aoifecahill** [comment]
yes, that's fine.
