### ISSUE TITLE
Only show "folds_file" warning when "folds_file" is specified

### ISSUE THREAD

**Issue by Lguyogiro** [EducationalTestingService/skll#404]
Currently, `config.py` logs the following warning
```
experiment - WARNING - Specifying "folds_file" overrides both explicit and default "num_cv_folds".
```
regardless of whether or not "folds_file" is specified, which is a little confusing. We should only log the warning when `folds_file` is specified.

**Comment by desilinguist** [comment]
Addressed by #405.
