### ISSUE TITLE
Return cv_results_ results in addition to best_score_ from grid_searcher

### ISSUE THREAD

**Issue by rgokul** [EducationalTestingService/skll#431]
For cross_validate task where we tune hyper parameters, often it is interesting to see plots of the performance of different hyper parameters on the train data. However, this is not possible because train() returns only the best score and the corresponding params.

I have made minor edits to dump it to a file for my needs but I would like to see this feature officially supported.

**Comment by desilinguist** [comment]
Interesting idea. Thanks!

**Comment by desilinguist** [comment]
Addressed by #471.
