### ISSUE TITLE
Add feature scaling to boston example

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#469]
The bottom example is a regression example and we should be doing feature scaling since we have numeric features on different scales in the original input.

**Comment by bndgyawali** [comment]
I am starting to work on this. Do you think I create a new configuration file with scaling, or add feature scaling to the existing configurations?

**Comment by desilinguist** [comment]
Just add it to the existing configuration file.

**Comment by desilinguist** [comment]
Addressed by #478.
