### ISSUE TITLE
Possible bug in `generate_predictions`

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#484]
Since `_pos_index` is an integer and `learner.label_dict` maps strings to integers, [this line](https://github.com/EducationalTestingService/skll/blob/67587d4947ea0cfe3f3373d1e35c3bdf45568052/skll/utilities/generate_predictions.py#L94) may have a bug. 

I suspect we haven't run into this before because the labels we use are also generally 1, 2, 3, 4 etc. @aoifecahill @Lguyogiro do you have any thoughts on this? Also, `Learner.predict()` seems to not have this issue which is probably another reason we missed this.

Thanks to @slava92 for originally reporting this issue!

**Comment by aoifecahill** [comment]
Yes, it looks like the test for `generate_predictions` uses integer labels and so we didn't notice this bug.

**Comment by desilinguist** [comment]
Yeah, this would have raised an exception if we were using string labels so I guess we have never really used `generate_predictions` with string labels :)

**Comment by desilinguist** [comment]
Addressed by #485.
