### ISSUE TITLE
Change default grid search folds

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#487]
The scikit-learn folks are planning to change the default number of CV splits for all kinds of cross-validation splitters from 3 to 5 since 3 has too much variance. 

Should we also do this in for our default `grid_search_fold` and `SKLL_MAX_CONCURRENT_PROCESSES` values?  This would mean our SGE workflows would change to require 5 slots instead of 3 whenever we run on the grid. However, as we have also seen, variance among the folds is bad.

**Comment by desilinguist** [comment]
You can see the proposed change [here](https://scikit-learn.org/dev/modules/generated/sklearn.model_selection.GridSearchCV.html#sklearn.model_selection.GridSearchCV) under the `cv` parameter:

> Changed in version 0.22: cv default value if None changed from 3-fold to 5-fold.

**Comment by desilinguist** [comment]
@mulhod @aoifecahill @bndgyawali any thoughts here?

**Comment by mulhod** [comment]
I am definitely in favor of making this change. I've often wondered why we're making decisions based on 3 folds, anyway.

**Comment by desilinguist** [comment]
@aoifecahill do you concur? This would make experiments take longer though so keep that in mind.

**Comment by aoifecahill** [comment]
Yep, I agree that it makes sense to follow what the scikit-learn people are doing.
