### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#498]
The contributing guidelines is fairly up to date but just requires a few changes:

- [x] The `easy` tag has been replaced with the `good first issue` tag so we should fix that in this file.
- [x] We should say the that the PR description should link to the issue that it's trying to address.
- [x] We should say that folks who are internal to ETS do not necessarily need to fork, this is just for external collaborators.  
- [ ] We should say something about adding at least 2-3 reviewers to the submitted PR. 
- [ ] Add a link to the contributing guidelines in a new section in the main SKLL README.

**Comment by ananyaganesh** [comment]
Addressed by #503
