### ISSUE TITLE
Link to `quadratic_weighted_kappa` from RSMTool in documentation

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#512]
The [RSMTool implementation](https://github.com/EducationalTestingService/rsmtool/blob/master/rsmtool/utils.py#L736) works for both continuous and discrete values. We should move that implementation to SKLL and add clear documentation to tell folks that we are using this formulate.

**Comment by bndgyawali** [comment]
For this, do we copy over the formula from RSMTool to here?

**Comment by desilinguist** [comment]
Yes, as soon as [this RSMTool PR](https://github.com/EducationalTestingService/rsmtool/pull/301) gets merged which should be today.

**Comment by desilinguist** [comment]
Actually, I think, at this point, we should just leave that implementation in RSMTool and simply link to that in the documetnation so that people can install RSMTool if they want that metric.
