### ISSUE TITLE
Force `ids` to be strings for pandas-based readers

### ISSUE THREAD

**Issue by jbiggsets** [EducationalTestingService/skll#537]
Currently in the `master` branch, if the user provides an ID column for the `CSVReader` or `TSVReader` classes, the IDs will automatically converted to the appropriate data type (`int` or `float`) if they are numeric, rather than being kept as strings. However, this is inconsistent with the _old_ behavior of these two classes, which  causes some downstream impacts if the reader wants to use a folds file. 

We should fix this for now by forcing the IDs to strings (unless `ids_to_floats` is passed), but we should also try to think of a better solution in the future. (I will file a separate issue to that effect.)

**Comment by desilinguist** [comment]
Addressed by #539
