### ISSUE TITLE
Run example configs as part of tests

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#544]
Lately we've encountered some issues where we don't realize that changes being introduced are breaking the examples (in generating the data or actually running the configs). Typically, we don't try each of the example configs every time we make a change, instead relying on the unit tests for that. So, we should create tests that simply generate the example data and run the configs. It might be a little challenging for one of the example data-sets since you have to retrieve it from the Kaggle site. (Update: Let's just download the required files and commit them to `skll`.)

**Comment by bndgyawali** [comment]
Can we not add that dataset somewhere for free and does not require authentication and use it for test purposes?

**Comment by desilinguist** [comment]
I agree with @bndgyawali. I feel like we can just commit the titanic dataset from Kaggle to our repo since it's just for our example anyway and plus that competition is so old - they are not changing the data in anyway.

**Comment by mulhod** [comment]
Yes, that would be great. I will modify the issue.

**Comment by jbiggsets** [comment]
Test the following:

## titanic
- [ ] `cross_validate.cfg`
- [ ] `evaluate_tuned.cfg`
- [ ] `evaluate.cfg`
- [ ] `learning_curve.cfg`
- [ ] `predict_train_only_tuned.cfg`
- [ ] `predict_train_only.cfg`
- [ ] `predict_train+dev_tuned.cfg`
- [ ] `predict_train+dev.cfg`
- [ ] `train.cfg`

## boston
- [ ] `cross_vali.cfg`
- [ ] `evaluate.cfg`

## iris
- [ ] `cross_vali.cfg`
- [ ] `evaluate.cfg`

**Comment by desilinguist** [comment]
Addressed by #546
