### ISSUE TITLE
Not all metrics being computed

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#564]
If you specify multiple tuning objectives in the `Tuning` section of the config and multiple metrics in the `Output` section of the config, the output metrics are only computed for a metric if it does not appear in the `Tuning` section. 

This does not make sense in the case where you specify multiple objective metrics in the `Tuning` section, since you only want to suppress the calculation of the specific tuning objective in a single experiment, not all possible tuning objectives across all experiments. 

**More concretely**
In Tuning I specify the following: `objectives=[f1_score_weighted, accuracy, precision, average_precision, roc_auc]`
and then in output, I specify the following: `metrics=[f1_score_weighted, accuracy, precision, recall, roc_auc, average_precision]`
But say the `f1_score_weighted` metric will only be computed on the test data in the case where I am tuning on f1_score_weighted. And it will get reported under the grid_objective column in the summary file 
I would like it to also get computed (as an additional metric) when I am tuning on `accuracy`, `precision`, `average_precision`,  and `roc_auc`. 

I think this means the check for what metrics to exclude from calculation needs to be moved from [`config.py`](https://github.com/EducationalTestingService/skll/blob/master/skll/config.py#L840) to `learner.py`.

**Comment by desilinguist** [comment]
Addressed by #567
