### ISSUE TITLE
python3 not explicitly listed in conda requirements file

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#575]
Depending on how you setup conda you could still get python 2.7 as your default.

**Comment by desilinguist** [comment]
Good catch! I will fix this in the release PR.

**Comment by aoifecahill** [comment]
It seems that even if you have python 2.7 in your base conda environment, creating the conda environment using the conda_requirements file does indeed get you python 3.7. 

Nevermind. Sorry about that!
