### ISSUE TITLE
Add nose as requirement in Contributing docs

### ISSUE THREAD

**Issue by asishm** [EducationalTestingService/skll#581]
Currently, the contributing documentation recommends creating a conda environment using `conda create -n sklldev -c conda-forge --file conda_requirements.txt`, and also recommends running `nosetests` to run the tests locally, but `conda_requirements.txt` doesn't list `nose` as a required library.

I'm not sure if `nose` should be added in the requirements file though as it's not needed for the core functionality.

**Comment by desilinguist** [comment]
Good catch! We can either add `nose` to the requirements or just add modify the `conda` command to be:

`conda create -n sklldev -c conda-forge nose --file conda_requirements.txt` which will also install `nose` along with the rest of the requirements.

**Comment by desilinguist** [comment]
This was addressed in the v2 release.
