### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#625]
This is a good reference: https://medium.com/faun/git-step-by-step-renaming-a-master-branch-to-main-16390ca7577b

**Comment by srhrshr** [comment]
@desilinguist , I've raised a PR #626 to help with this change. Please have a look into it and let me know if I might have overlooked something. Thanks!

**Comment by desilinguist** [comment]
Thanks for your help @srhrshr !
