### ISSUE TITLE
Rewrite docstrings to match scikit-learn style and show type hints correctly.

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#647]
We should try and match the way that scikit-learn writes their docstrings. [Here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/linear_model/_huber.py#L125) is an example. 

For example, there is a blank line between the parameters and the default values are indicated right after the parameter type. It's also nice how the types that are numpy arrays also include the shapes.

**Comment by RobertImbrie** [comment]
Hey @desilinguist! Finally have some time to get started on this again.

I noticed there's inconsistencies between how we write boolean docstrings and how scikit writes them. Even worse, scikit itself is inconsistent with how it writes boolean docstrings!

I want to make our documentation for booleans consistent. That leaves with us three options:

**skll's current method:** Should we do X or not?
**scikit method 1:** If ``True``, do X.
**scikit method 2:** Whether or not to do X.

I'm leaning towards scikit method 1, though I also don't want to make any unilateral changes. What are your thoughts?

**Comment by desilinguist** [comment]
Welcome back @RobertImbrie! We really appreciate your contributions. 

That's a very interesting finding regarding Boolean docstrings! I think I also agree with your thinking and like scikit option 1 - the most important thing is consistency. 

What do you think @mulhod @Frost45  @aoifecahill?

**Comment by mulhod** [comment]
Yeah, sounds good. I agree about merely being consistent.
