### ISSUE TITLE
Incomplete 'push' instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by RobertImbrie** [EducationalTestingService/skll#680]
CONTRIBUTING.md gives the following commands for pushing to a new branch, which can be found in steps 7-10:
```
$ git checkout -b feature/my-new-addition
$ git add modified_files
$ git commit
$ nosetests
$ git push feature/my-new-addition
```

Whenever I follow those steps, I am given the error EDIT: when using `git push feature/my-new-addition`:
```
fatal: 'feature/my-new-addition' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

This error occurs for both my fork and the main repository. It has been an issue since I started contributing to skll.

In the past, I circumvented the issue on my fork by using `git push origin feature/my-new-addition` instead. However, now that I'm using the main repository, I want to make sure I'm doing it the right way. What's the proper way to push a branch and can I update CONTRIBUTING.md to match that?

**Comment by RobertImbrie** [comment]
I get the error when using `git push feature/my-new-addition`, where `my-new-addition` is the new branch. I've added a link to a screenshot [here](https://gyazo.com/69b994cfd5f09459052a4af96fb7efb6).

**Comment by desilinguist** [comment]
Oh I see. Yeah, that's definitely outdated. It should be replaced with `git push -u origin feature/my-new-addition`.

**Comment by RobertImbrie** [comment]
Great! I'll make the changes in `CONTRIBUTING.md` and do a pull request.
