### ISSUE TITLE
Allow passing of sample weights to fit()

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#692]
It would be nice to be able to provide a file containing sample weights for them to be passed along to the `sample_weight` argument of fit().

**Comment by desilinguist** [comment]
You mean, pass a file to `train()` which then passes it to sklearn `fit()`?

**Comment by aoifecahill** [comment]
yes :)

**Comment by desilinguist** [comment]
Should be easy enough.

**Comment by bndgyawali** [comment]
how different is this from this issue?
https://github.com/EducationalTestingService/skll/issues/182?_pjax=%23js-repo-pjax-container

I have a branch half done about the instance weight but never got priority for a long time.

**Comment by aoifecahill** [comment]
It's the same, I searched for that issue because I knew you had worked on it before, but somehow couldn't find it 🤦‍♀️

**Comment by desilinguist** [comment]
So, shall we close this issue @aoifecahill ?

**Comment by aoifecahill** [comment]
Duplicates #182
