### ISSUE TITLE
sci-kit learn + conda-forge feedstock

### ISSUE THREAD

**Issue by ngam** [EducationalTestingService/skll#698]
Hi! Great work here. 

Are there plans to relax the scikit-learn dependency or adapt to the 1.x release?

https://github.com/EducationalTestingService/skll/blob/4ead823bdbd06603daa20431e3a1f3cbe6e88d1f/requirements.txt#L1-L9

Also, I have started a feedstock to make skll available via conda-forge (https://github.com/conda-forge/skll-feedstock). You're welcome to maintain the conda-forge feedstock with me (and please feel free to let me know if you have any issues that need to be corrected).

Thanks!

**Comment by desilinguist** [comment]
Wow, this is great @ngam ! We have had plans to add SKLL to conda-forge for a while but never got around to it. Thank you so much for doing so! We would be happy to take a look at the feedstock and are happy to co-maintain it with you! 

Yes, we absolutely plan to upgrade scikit-learn to v1.0 soon (probably January).

**Comment by ngam** [comment]
Perfect, add yourselves to the feedstock whenever you want and I can approve it. I have also seen your other tests for skll, and will be good to incorporate these in the feedstock as well. The major difference between what I have done and your previous builds is that I opted for a noarch build, which makes things a little easier.

**Comment by desilinguist** [comment]
We used to have noarch builds too but they tended not to work correctly for us in some cases mostly, we suspect, due to issues with `beautifulsoup`. However, it’s probably resolved now.

**Comment by desilinguist** [comment]
@ngam we have just merged support for scikit-learn 1.0. I will work on a few new issues and then will release 3.0.0. Once we are ready, we will try noarch builds on our end again.

**Comment by desilinguist** [comment]
@ngam we have just released 3.0.0!
