### ISSUE TITLE
Interactive examples for skll

### ISSUE THREAD

**Issue by edublancas** [EducationalTestingService/skll#753]
Hi skll team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a Binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor skll with some computing power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by desilinguist** [comment]
Hi @edublancas, thank you so much for your gracious offer. I think we don't really need any additional compute for now but if we do, we'll get in touch. Thanks again!

**Comment by edublancas** [comment]
appreciate the response!
